config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/create'

  get 'user_sessions/destroy'

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'main_pages#intro'
  get '/index' => 'main_pages#index'
  get '/main_posts' => 'main_pages#posts'
 
  get '/admin' => 'admins#index'
  get "/auth/:provider/callback" => "user_sessions#create"
  get '/cart' => "main_pages#cart"
  get '/photos/:id/:post_id' => "photos#show"
  resources :posts
  resources :carts, only: [:show, :destroy]
  resources :sessions, only: [:create, :destroy]
  resources :line_items, only: [:create, :destroy]
  
  resources :authors, only: [:update, :show, :create] 
  resources :photos, only: [:create, :show]
  resources :comments, only: [:create, :show]
  get "robots.txt" => "main_pages#robots", defaults: {format: 'txt'}, as: :robots
  get "sitemap.xml" => "main_pages#sitemap",  defaults: {format: :xml}, as: :sitemap
  

end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController

  def intro
  end
  
  def index
  end
  def cart
  end

  def robots
  end

  def sitemap
    path = Rails.root.join("public", "sitemaps", "sitemap.xml")
    if File.exists?(path)
      render xml: open(path).read
    else
      render text: "Sitemap not found.", status: :not_found
    end
  end

  def posts
    @posts = Post.all_public
    render json: {posts: @posts}
  end
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/views/main_pages/cart.html.haml
%body.cart-bg(ng-controller="CartCtrl")
  .container-fluid
    .col-xs-12

      .button-group.pull-left.arrow-buttons-left
        %button.btn(ng-click="clean_cart()" ng-if="full_flag" ng-hide="empty_flag")  
          Очистить 
          %i.fa.fa-book.fa-2x
      .button-group.pull-right.arrow-buttons-right
       
          
        
        %button.btn-sky.btn(ng-hide="empty_flag" ng-if="full_flag" ng-click="power_off()")
          %i.fa.fa-power-off.fa-2x
        
        %a.btn.btn-sky(href=index_path )
          %i.fa.fa-dashboard.fa-2x
     
        

        %button.btn-sky.btn.sort(ng-click="subTab()") 
          %i.fa.fa-arrow-left.fa-2x
        %button.btn-sky.btn(ng-click="addTab()")
          %i.fa.fa-arrow-right.fa-2x
      
    .col-md-12
      .row
        .container-main(ng-hide="power_flag" )
          .view.view-tenth.post.anima.square( ng-repeat="post in p" )

            %figure(ng-class="is_asset(post.asset.url)")
              %img(ng-if="post.asset.url" src="{{post.asset.url }}")       

              %figcaption.mask
                %h4.base-class(ng-bind-html="post.title")
                  
                %p(ng-bind-html="post.title")
                %p

                %a.info(ng-click="clicked('run')" href="/posts/{{post.id}}")
                  %i.fa.fa-arrow-up.fa-2x
                
                %a.destroy(href="#" ng-click="delete_post(post.id, $index)"   data-toggle="tooltip" data-placement="bottom" title="Удалить из читаемого")
                  %i.fa.fa-close.fa-2x

app/views/main_pages/index.html.haml
- meta title: "Игра начинается", description: "Здесь есть все, чтобы достичь ничего", keywords: %w(наркотики игры секс желания постмодерн)

%body.bg
  .container-fluid(ng-controller="MountCtrl")
    = image_tag("bg/cloud1.png", class: "cloud img-responsive col-xs-1 x1")
    = image_tag("bg/cloud2.png", class: "cloud img-responsive col-xs-3 x2")
    = image_tag("bg/cloud3.png", class: "cloud img-responsive col-xs-2 x3")
    = image_tag("bg/cloud1.png", class: "cloud img-responsive col-xs-1 x4")
    = image_tag("bg/cloud2.png", class: "cloud img-responsive col-xs-4 x5")
    = image_tag("bg/cloud3.png", class: "cloud img-responsive col-xs-2 x6")
    
   
    .col-xs-12
      
        
      .button-group.pull-right.arrow-buttons-right
       
          
       
        %button.btn-sky.btn(ng-click="power_off()")
          %i.fa.fa-power-off.fa-2x
        %a.btn-sky.btn(href="/cart")
          %i.fa.fa-book.fa-2x

        %button.btn-sky.btn.sort(ng-click="subTab()") 
          %i.fa.fa-arrow-left.fa-2x
        %button.btn-sky.btn(ng-click="addTab()")
          %i.fa.fa-arrow-right.fa-2x
      
    .col-md-12
      .row
        .col-md-12      
          //%h2 Choose your level
            
          .container-main(ng-hide="power_flag" )
           
            //.grid.mix(ng-repeat="post in p" class="{{isClass(post)}} " data-myorder="{{post.id}}" )
            
            .view.view-tenth.post.anima.square( ng-repeat="post in p" )
              
              %figure(ng-class="is_asset(post.asset.url)")
                %img(ng-if="post.asset.url" src="{{post.asset.url }}")       

                %figcaption.mask
                  %h4.base-class(ng-bind-html="post.title")
                   
                  %p(ng-bind-html="post.description")
                  
                  
                  %a.info( href="/posts/{{post.id}}")
                    %i.fa.fa-arrow-up.fa-2x.base-class(class="{{myVar1}}")
                  %a.info(href="#" ng-click="add_post(post.id, 'my-class', $index)" data-toggle="tooltip" data-placement="bottom" title="Прочитать потом")
                    %i.fa.fa-pause.fa-2x.base-class(class="{{p[$index].myVar}}")

              
     

    
    

app/views/main_pages/intro.html.haml
%body.intro-body
  = image_tag("intro/logo.png", id: "logo")
  = image_tag("intro/start.png", id: "start")

app/views/main_pages/robots.text.erb
# See http://www.robotstxt.org/robotstxt.html for documentation on how to use the robots.txt file
#
# To ban all spiders from the entire site uncomment the next two lines:
User-agent: *
Disallow: /tmp/
Disallow: /admin/*
Disallow: /cart/
Sitemap: <%= sitemap_url %>